name: Rebuild and Push Watchtower

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly build
  workflow_dispatch:

jobs:
  pull-retag-push:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull latest Watchtower image
        run: docker pull containrrr/watchtower:latest

      - name: Retag with custom name
        run: docker tag containrrr/watchtower:latest ${{ secrets.DOCKERHUB_USERNAME }}/mytower:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mytower:latest
